table Medidas
	lineageTag: 0512c956-6ca3-4f5d-b6d9-9296bf57a01f

	measure Faturamento = SUM(fVendas[valor_total])
		formatString: #,0.00
		displayFolder: GERAL
		lineageTag: a5d70e88-52c0-4d3d-8469-7f00ff321b4a

	/// Soma total dos custos de venda. Ajuda a calcular a margem de lucro.
	measure Custo = SUM(fVendas[custo_da_venda])
		formatString: #,0.00
		displayFolder: GERAL
		lineageTag: 5a0976e9-5b6d-46ae-a75a-8037720bbedb

	/// Quantidade total de produtos vendidos. Mostra o volume de vendas em unidades.
	measure 'Qtd Produtos Vendidos' = SUM(fVendas[quantidade_vendida_produto])
		formatString: #,0
		displayFolder: GERAL
		lineageTag: 0103f18a-4ebb-4332-8a6b-9d5e6d3ad687

	/// Valor médio pelo qual os produtos foram vendidos. Útil para acompanhar variações de preço.
	measure 'Preço Médio Venda' = AVERAGE(fVendas[valor_unitario_produto])
		formatString: 0.00
		displayFolder: GERAL
		lineageTag: 4a515e05-fd5b-412b-9640-f4b18fce196e

	/// Soma do valor de tabela (preço cheio) dos produtos. Pode indicar valor total sem descontos.
	measure 'Total Tabela' = SUM(fVendas[valor_tabela_de_preco_do_produto])
		displayFolder: GERAL
		lineageTag: f95804ef-4705-4b79-9e8a-34aa7451401d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Média do preço de tabela dos produtos. Serve de referência para comparação com o preço real de venda.
	measure 'Preço Médio Tabela' = AVERAGE(fVendas[valor_tabela_de_preco_do_produto])
		formatString: 0.00
		displayFolder: GERAL
		lineageTag: fe37cd01-886f-4078-93e7-40c1f87526e8

	/// Mostra a diferença percentual entre o preço de tabela e o preço real praticado. Útil para entender descontos médios.
	measure '% Var Preço Tabela' = ```
			DIVIDE(
			    ([Preço Médio Tabela] - [Preço Médio Venda]),
			    ([Preço Médio Venda])
			) 
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: GERAL
		lineageTag: 12d7cf36-8bbf-415f-aa35-e6830940f267

	/// Lucro bruto obtido ao subtrair o custo da venda do faturamento.
	measure Margem = [Faturamento] - [Custo]
		displayFolder: GERAL
		lineageTag: 834539d2-2760-48d7-914d-bacf559d8621

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Porcentagem da margem em relação ao faturamento. Indica a rentabilidade.
	measure '% Margem' = DIVIDE([Margem],[Faturamento])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: GERAL
		lineageTag: e32e9382-a4e6-4cec-8858-64ba4e6b1434

	measure 'Bars Label' = ```
			
			VAR vFatTotal = 
			CALCULATE(
			    [Faturamento],
			    ALLSELECTED(dCliente[descricao_cliente])
			)
			RETURN
			SELECTEDVALUE( dCliente[descricao_cliente]) &
			" (" &
			FORMAT(DIVIDE([Faturamento], vFatTotal), "0.00%") &
			")"
			```
		displayFolder: UX
		lineageTag: a96d12fe-7c2f-45c1-be43-4043ee468cb1

	/// Seleciona os produtos com maior faturamento. Útil para destacar os mais lucrativos.
	measure 'Top N Recomendation  Produtos' = ```
			
			VAR vN = 3
			VAR vTopN =
			TOPN(
			    vN,
			    ALLSELECTED(dProduto),
			    [Faturamento] / 1000000, // Ordena por GROSS PROFIT e usa TOTAL REVENUE como critério de desempate
			    DESC
			)
			VAR vItens =
			CONCATENATEX(
			    vTopN,
			    dProduto[descricao_produto],
			    ", ", 
			    [Faturamento], // Ordem primária por GROSS PROFIT
			    DESC // Descendente
			)
			RETURN
			    "💡Os produtos com maior Faturamento são: " & vItens
			
			```
		displayFolder: UX
		lineageTag: 77777706-8c3d-48be-b4f6-6bb8300c99ac

	measure Dummy = 0
		formatString: 0
		displayFolder: UX
		lineageTag: 6bcc58ac-7da4-4a72-98d8-9eaa030b44cc

	/// Variação percentual do faturamento em relação ao mesmo período do ano anterior.
	measure '% Faturamento YoY' = ```
			
			VAR vIndicadorLY = 
			CALCULATE ( 
			    [Faturamento],
			    SAMEPERIODLASTYEAR(dCalendario[Data])
			)
			
			VAR vResultado = DIVIDE ( [Faturamento] - vIndicadorLY, vIndicadorLY )
			
			RETURN
			    vResultado
			```
		displayFolder: TEMPO
		lineageTag: 5139a384-66b7-421c-a548-5b1b89034adf

		formatStringDefinition = "⇧ 0.00% vs ano anterior;⇩ 0% vs vs ano anterior"

	/// Variação percentual do custo em relação ao mesmo período do ano anterior.
	measure '% Custo YoY' = ```
			
			VAR vIndicadorLY = 
			CALCULATE ( 
			    [Custo],
			    SAMEPERIODLASTYEAR(dCalendario[Data])
			)
			
			VAR vResultado = DIVIDE ( [Custo] - vIndicadorLY, vIndicadorLY )
			
			RETURN
			    vResultado
			```
		displayFolder: TEMPO
		lineageTag: 142e8ee6-f174-42c3-8bb3-83ec4cd7a7c9

		formatStringDefinition = "⇧ 0.00% vs ano anterior;⇩ 0% vs vs ano anterior"

	/// Variação da margem comparando com o mesmo período do ano anterior.
	measure '% Margem YoY' = ```
			
			VAR vIndicadorLY = 
			CALCULATE ( 
			    [% Margem],
			    SAMEPERIODLASTYEAR(dCalendario[Data])
			)
			
			VAR vResultado = DIVIDE ( [% Margem] - vIndicadorLY, vIndicadorLY )
			
			RETURN
			    vResultado
			```
		displayFolder: TEMPO
		lineageTag: 640e3853-d94a-4f11-83fd-78c27f555da5

		formatStringDefinition = "⇧ 0.00% vs ano anterior;⇩ 0% vs vs ano anterior"

	/// Variação no preço médio de venda comparado ao mesmo período do ano anterior.
	measure '% Preço Media de Venda YoY' = ```
			
			VAR vIndicadorLY = 
			CALCULATE ( 
			    [Preço Médio Venda],
			    SAMEPERIODLASTYEAR(dCalendario[Data])
			)
			
			VAR vResultado = DIVIDE ( [Preço Médio Venda] - vIndicadorLY, vIndicadorLY )
			
			RETURN
			    vResultado
			```
		displayFolder: TEMPO
		lineageTag: 3f52f542-f852-4fe2-9bce-c912fb258855

		formatStringDefinition = "⇧ 0.00% vs ano anterior;⇩ 0% vs vs ano anterior"

	/// Soma total do valor unitário dos produtos vendidos.
	measure 'Total Produto' = SUM(fVendas[valor_unitario_produto])
		displayFolder: GERAL
		lineageTag: 351cf550-6854-47b5-be7a-bcc8c93ae839

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Variação no preço médio de tabela em relação ao mesmo período do ano anterior.
	measure '% Preço Media de Tabela YoY' = ```
			
			VAR vIndicadorLY = 
			CALCULATE ( 
			    [Preço Médio Tabela],
			    SAMEPERIODLASTYEAR(dCalendario[Data])
			)
			
			VAR vResultado = DIVIDE ( [Preço Médio Tabela] - vIndicadorLY, vIndicadorLY )
			
			RETURN
			    vResultado
			```
		displayFolder: TEMPO
		lineageTag: 8aca8d3c-1a53-4d75-9203-83ed6717bb18

		formatStringDefinition = "⇧ 0.00% vs ano anterior;⇩ 0% vs vs ano anterior"

	measure 'Indicador LY' = ```
			
			CALCULATE ( 
			    [Faturamento],
			    SAMEPERIODLASTYEAR(dCalendario[Data])
			)
			```
		displayFolder: UX
		lineageTag: 513139d2-ad21-4d3c-b734-84093a0af568

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure HTML_GUIDE =
			"<html>
			    <head>
			        <style>
			            body {
			                font-family: Arial, sans-serif;
			                background-color: #f8f8f8;
			                margin: 0;
			                padding: 0;
			                width: 1280px; /* Largura fixa de 1280px */
			                height: 720px; /* Altura fixa de 720px */
			                overflow: hidden; /* Garantir que não tenha barras de rolagem */
			            }
			
			            .guide-container {
			                width: 100%;
			                height: 100%;
			                max-width: 1280px;
			                margin: auto;
			                background-color: #fff;
			                padding: 20px;
			                border-radius: 8px;
			                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
			                overflow-y: auto; /* Permite rolagem no conteúdo se necessário */
			            }
			
			            .guide-title {
			                font-size: 36px;
			                font-weight: bold;
			                color: #333;
			                margin-bottom: 30px;
			                text-align: left;
			            }
			
			            .button-item {
			                display: flex;
			                align-items: center;
			                padding: 15px 0;
			                border-bottom: 1px solid #ddd;
			            }
			
			            .button-item:last-child {
			                border-bottom: none;
			            }
			
			            .button-icon {
			                width: 30px;
			                height: 30px;
			                margin-right: 20px; /* Espaçamento entre ícone e texto */
			            }
			
			            .button-name {
			                font-size: 20px;
			                font-weight: bold;
			                color: #0066cc;
			            }
			
			            .button-description {
			                font-size: 16px;
			                color: #555;
			                margin-top: 5px;
			            }
			
			            .button-item + .button-item {
			                margin-top: 20px;
			            }
			
			            .guide-item {
			                display: flex;
			                align-items: center;
			                padding: 15px 0;
			                border-bottom: 1px solid #ddd;
			            }
			
			            .guide-item:last-child {
			                border-bottom: none;
			            }
			
			            .guide-item-icon {
			                width: 30px;
			                height: 30px;
			                margin-right: 20px;
			            }
			
			            .guide-item-description {
			                font-size: 16px;
			                color: #555;
			                margin-top: 5px;
			            }
			
			            .guide-item + .guide-item {
			                margin-top: 20px;
			            }
			        </style>
			    </head>
			    <body>
			        <div class='guide-container'>
			
			            <!-- Drill Up -->
			            <div class='button-item'>
			                <div class='button-icon'>
			                    <svg width='16' height='31' viewBox='0 0 16 31' fill='none' xmlns='http://www.w3.org/2000/svg'>
			                        <path d='M7 30C7 30.5523 7.44772 31 8 31C8.55228 31 9 30.5523 9 30L7 30ZM8.70711 0.292893C8.31658 -0.0976311 7.68342 -0.0976311 7.29289 0.292893L0.928931 6.65685C0.538407 7.04738 0.538407 7.68054 0.928931 8.07107C1.31946 8.46159 1.95262 8.46159 2.34314 8.07107L8 2.41421L13.6569 8.07107C14.0474 8.46159 14.6805 8.46159 15.0711 8.07107C15.4616 7.68054 15.4616 7.04738 15.0711 6.65685L8.70711 0.292893ZM8 30L9 30L9 1L8 1L7 1L7 30L8 30Z' fill='black'/>
			                    </svg>
			                </div>
			                <div>
			                    <div class='button-name'>Drill Up</div>
			                    <div class='button-description'>Após a seleção deste ícone, os dados serão apresentados a um nível acima da hierarquia atual. Permanecerá desabilitado quando os dados apresentados corresponderem ao nível máximo da hierarquia. </div>
			                </div>
			            </div>
			
			            <!-- Ir para o próximo nível da hierarquia -->
			            <div class='button-item'>
			                <div class='button-icon'>
			                   <svg width='32' height='31' viewBox='0 0 32 31' fill='none' xmlns='http://www.w3.org/2000/svg'>
			                        <path d='M25 1C25 0.447715 24.5523 0 24 0C23.4477 0 23 0.447715 23 1L25 1ZM23.2929 30.7071C23.6834 31.0976 24.3166 31.0976 24.7071 30.7071L31.0711 24.3431C31.4616 23.9526 31.4616 23.3195 31.0711 22.9289C30.6805 22.5384 30.0474 22.5384 29.6569 22.9289L24 28.5858L18.3431 22.9289C17.9526 22.5384 17.3195 22.5384 16.9289 22.9289C16.5384 23.3195 16.5384 23.9526 16.9289 24.3431L23.2929 30.7071ZM24 1L23 1L23 30H24H25L25 1L24 1Z' fill='black'/>
			                        <path d='M9 1C9 0.447715 8.55228 0 8 0C7.44772 0 7 0.447715 7 1L9 1ZM7.29289 30.7071C7.68342 31.0976 8.31658 31.0976 8.70711 30.7071L15.0711 24.3431C15.4616 23.9526 15.4616 23.3195 15.0711 22.9289C14.6805 22.5384 14.0474 22.5384 13.6569 22.9289L8 28.5858L2.34315 22.9289C1.95262 22.5384 1.31946 22.5384 0.928932 22.9289C0.538408 23.3195 0.538408 23.9526 0.928932 24.3431L7.29289 30.7071ZM8 1L7 1L7 30H8H9L9 1L8 1Z' fill='black'/>
			                    </svg>
			                </div>
			                <div>
			                    <div class='button-name'>Ir para o próximo nível da hierarquia</div>
			                    <div class='button-description'>Após a seleção deste ícone, os dados serão apresentados um nível abaixo da hierarquia atual. </div>
			                </div>
			            </div>
			
			            <!-- Expandir campo -->
			            <div class='button-item'>
			                <div class='button-icon'>
			                  <svg width='32' height='28' viewBox='0 0 32 28' fill='none' xmlns='http://www.w3.org/2000/svg'>
			<path d='M25 12C25 11.4477 24.5523 11 24 11C23.4477 11 23 11.4477 23 12H25ZM23.2929 27.7071C23.6834 28.0976 24.3166 28.0976 24.7071 27.7071L31.0711 21.3431C31.4616 20.9526 31.4616 20.3195 31.0711 19.9289C30.6805 19.5384 30.0474 19.5384 29.6569 19.9289L24 25.5858L18.3431 19.9289C17.9526 19.5384 17.3195 19.5384 16.9289 19.9289C16.5384 20.3195 16.5384 20.9526 16.9289 21.3431L23.2929 27.7071ZM24 12H23L23 27H24H25L25 12H24Z' fill='black'/>
			<path d='M9 12C9 11.4477 8.55228 11 8 11C7.44772 11 7 11.4477 7 12H9ZM7.29289 27.7071C7.68342 28.0976 8.31658 28.0976 8.70711 27.7071L15.0711 21.3431C15.4616 20.9526 15.4616 20.3195 15.0711 19.9289C14.6805 19.5384 14.0474 19.5384 13.6569 19.9289L8 25.5858L2.34315 19.9289C1.95262 19.5384 1.31946 19.5384 0.928932 19.9289C0.538408 20.3195 0.538408 20.9526 0.928932 21.3431L7.29289 27.7071ZM8 12H7L7 27H8H9L9 12H8Z' fill='black'/>
			<line x1='8' y1='12' x2='24' y2='12' stroke='black' stroke-width='2'/>
			<line x1='16' y1='12' x2='16' y2='1' stroke='black' stroke-width='2' stroke-linecap='round'/>
			</svg>
			
			
			                </div>
			                <div>
			                    <div class='button-name'>Expandir todo o campo um nível abaixo na hierarquia</div>
			                    <div class='button-description'>Após a seleção deste ícone, os dados serão apresentados um nível abaixo da hierarquia atual, exibindo toda a linha da hierarquia até este nível. Ele estará habilitado enquanto o nível mais alto da hierarquia estiver sendo exibido e até que toda a hirarquia dispoível seja apresentada. </div>
			                </div>
			            </div>
			
			            <!-- Drill Down -->
			            <div class='button-item'>
			                <div class='button-icon'>
			                   <svg width='16' height='31' viewBox='0 0 16 31' fill='none' xmlns='http://www.w3.org/2000/svg'>
			<path d='M9 1C9 0.447715 8.55228 0 8 0C7.44772 0 7 0.447715 7 1L9 1ZM7.29289 30.7071C7.68342 31.0976 8.31658 31.0976 8.70711 30.7071L15.0711 24.3431C15.4616 23.9526 15.4616 23.3195 15.0711 22.9289C14.6805 22.5384 14.0474 22.5384 13.6569 22.9289L8 28.5858L2.34315 22.9289C1.95262 22.5384 1.31946 22.5384 0.928932 22.9289C0.538408 23.3195 0.538408 23.9526 0.928932 24.3431L7.29289 30.7071ZM8 1L7 1L7 30H8H9L9 1L8 1Z' fill='black'/>
			</svg>
			                </div>
			                <div>
			                    <div class='button-name'>Clique aqui para habilitar o Drill Down</div>
			                    <div class='button-description'>Após a seleção deste ícone, será apresentado o mesmo preenchido para que o usuário selecione um dado. Após a seleção, os dados serão apresentados um nível abaixo da hierarquia atual do dado selecionado.</div>
			                </div>
			            </div>
			
			            <!-- Filtros e Segmentações -->
			            <div class='button-item'>
			                <div class='button-icon'>
			                    <svg width='28' height='26' viewBox='0 0 28 26' fill='none' xmlns='http://www.w3.org/2000/svg'>
			                        <path d='M26.3298 1.5H1.67017C1.23005 1.5 1.00463 2.02757 1.30885 2.34561L11.3529 12.8462C11.4469 12.9445 11.4968 13.0768 11.4911 13.2126L11.0217 24.4792C11.0099 24.7632 11.237 25 11.5213 25H16C16.2761 25 16.5 24.7761 16.5 24.5V13.2006C16.5 13.0719 16.5497 12.9481 16.6387 12.855L26.6912 2.34561C26.9954 2.02757 26.7699 1.5 26.3298 1.5Z' stroke='black' stroke-width='2'/>
			                    </svg>
			                </div>
			                <div>
			                    <div class='button-name'>Filtros e Segmentações afetando este visual</div>
			                    <div class='button-description'>Apresenta os últimos filtros informados ou excluídos.</div>
			                </div>
			            </div>
			
			            <!-- Modo Foco -->
			            <div class='button-item'>
			                <div class='button-icon'>
			                    <svg width='27' height='22' viewBox='0 0 27 22' fill='none' xmlns='http://www.w3.org/2000/svg'>
			                        <path d='M13 1H2C1.72386 1 1.5 1.22386 1.5 1.5V20C1.5 20.2761 1.72386 20.5 2 20.5H13M13 20.5V13.5C13 13.2239 12.7761 13 12.5 13H2.5M13 20.5H25C25.2761 20.5 25.5 20.2761 25.5 20V13' stroke='black' stroke-width='2'/>
			                        <path d='M25.875 1C25.875 0.516751 25.4832 0.125 25 0.125H17.125C16.6418 0.125 16.25 0.516751 16.25 1C16.25 1.48325 16.6418 1.875 17.125 1.875H24.125V8.875C24.125 9.35825 24.5168 9.75 25 9.75C25.4832 9.75 25.875 9.35825 25.875 8.875V1ZM16 10L16.6187 10.6187L25.6187 1.61872L25 1L24.3813 0.381282L15.3813 9.38128L16 10Z' fill='black'/>
			                    </svg>
			                </div>
			                <div>
			                    <div class='button-name'>Modo Foco</div>
			                    <div class='button-description'> Ao clicar no ícone de Foco, você pode concentrar a visualização em uma área específica dos dados, destacando-os para facilitar a análise. Apresenta os daods de forma expandida.</div>
			                </div>
			            </div>
			
			            <!-- Mais Opções -->
			            <div class='button-item'>
			                <div class='button-icon'>
			                    <svg width='26' height='5' viewBox='0 0 26 5' fill='none' xmlns='http://www.w3.org/2000/svg'>
			                        <circle cx='2.5' cy='2.5' r='2.5' fill='black'/>
			                        <circle cx='13.5' cy='2.5' r='2.5' fill='black'/>
			                        <circle cx='23.5' cy='2.5' r='2.5' fill='black'/>
			                    </svg>
			                </div>
			                <div>
			                    <div class='button-name'>Mais Opções</div>
			                    <div class='button-description'>
			                        Clique para acessar opções adicionais, como:
			                        <ul>
			                            <li><strong>Exportar Dados:</strong> Permite a exportação dos dados em formato **XLSX** (máximo 150 mil linhas) ou **CSV** (máximo 30 mil linhas).</li>
			                            <li><strong>Mostrar Como Tabela:</strong> Exibe os dados do gráfico ou visual em formato de tabela, facilitando a visualização detalhada de todos os valores.</li>
			                            <li><strong>Destacar:</strong> Use para destacar um conjunto de dados ou valores no gráfico, facilitando a visualização de informações específicas.</li>
			                            <li><strong>Classificar em Ordem:</strong> Organize os dados em ordem crescente ou decrescente com base nos valores selecionados, como maior para menor ou vice-versa.</li>
			                        </ul>
			                    </div>
			                </div>
			            </div>
			        </div>
			    </body>
			</html>
			"
		displayFolder: DOCUMENTAÇÃO
		lineageTag: 517d3bb0-3171-41a3-aee8-ad616a2ded25

	measure HTML_Glossario = ```
			
			VAR _dados_documentacao = 
			    FILTER (
			        documentacao,
			        documentacao[Type] = "Measure" && documentacao[Description] <> BLANK()
			    )
			VAR _html = 
			    CONCATENATEX (
			        _dados_documentacao,
			        "<div class='glossary-item'>
			            <div class='glossary-item-name'>" & documentacao[Name] & "</div>
			            <div class='glossary-item-description'>" & documentacao[Description] & "</div>
			        </div>",
			        "<br/>",
			        documentacao[Name],
			        ASC
			    )
			RETURN 
			    "<html>
			        <head>
			            <style>
			                body {
			                    font-family: Arial, sans-serif;
			                    background-color: #f8f8f8;
			                    margin: 0;
			                    padding: 0;
			                    width: 1280px; /* Largura fixa de 1280px */
			                    height: 720px; /* Altura fixa de 720px */
			                    overflow: hidden; /* Garantir que não tenha barras de rolagem */
			                }
			
			                .glossary-container {
			                    width: 100%;
			                    height: 100%;
			                    max-width: 1280px;
			                    margin: auto;
			                    background-color: #fff;
			                    padding: 20px;
			                    border-radius: 8px;
			                    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
			                    overflow-y: auto; /* Permite rolagem no conteúdo se necessário */
			                }
			
			                .glossary-title {
			                    font-size: 36px;
			                    font-weight: bold;
			                    color: #333;
			                    margin-bottom: 30px;
			                    text-align: left;
			                }
			
			                .glossary-item {
			                    padding: 10px 0;
			                    border-bottom: 1px solid #ddd;
			                }
			
			                .glossary-item:last-child {
			                    border-bottom: none;
			                }
			
			                .glossary-item-name {
			                    font-size: 20px;
			                    font-weight: bold;
			                    color: #0066cc;
			                }
			
			                .glossary-item-description {
			                    font-size: 16px;
			                    color: #555;
			                    margin-top: 5px;
			                }
			
			                .glossary-item + .glossary-item {
			                    margin-top: 40px;
			                }
			            </style>
			        </head>
			                <body>
			            <div class='glossary-container'>
			                <div class='glossary-title'></div>"
			        & _html & "</div>
			    </body>
			    </html>"
			```
		displayFolder: DOCUMENTAÇÃO
		lineageTag: b2004794-3306-4a51-b453-9056a53db168

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

